sonar.sources=apps,libs
sonar.tests=apps,libs

sonar.test.inclusions=apps/**/*.spec.ts,apps/**/*.test.ts,libs/**/*.spec.ts,libs/**/*.test.ts
sonar.exclusions=apps/**/*.spec.ts,apps/**/*.test.ts,libs/**/*.spec.ts,libs/**/*.test.ts,**/*.controller.ts,**/*.repository.ts,**/*.client.ts,**/*.types.ts,**/*.errors.ts,apps/**/src/features/**/clients/**/*.ts,apps/**/src/features/**/registration/**,apps/**/src/features/**/password-*/**,apps/**/src/features/**/shared-auth/**,apps/**/src/features/**/current-user/**,apps/**/src/features/**/internal-user/**,apps/**/src/features/**/admin-users/**,apps/**/src/features/**/notifications/**,apps/**/src/features/**/integrations/**,apps/**/src/features/**/uploads/**,apps/**/src/features/**/geo/**,apps/**/src/features/**/shared-geo/**,apps/admin-service/src/features/users/admin-invitation-delivery.service.ts,libs/common/src/apicenter/**,libs/common/src/config/**,libs/common/src/supabase/**,**/node_modules/**,**/dist/**,**/coverage/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*.spec.ts,**/*.test.ts,**/*.types.ts,**/*.errors.ts,**/*.controller.ts,**/clients/**/*.ts

sonar.issue.ignore.multicriteria=e1,e2,e3,e4
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.ts
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S5332
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.ts
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S5122
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.ts
sonar.issue.ignore.multicriteria.e4.ruleKey=typescript:S4784
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.ts
