export const PH_CITIES: string[] = [
  // NCR (Metro Manila)
  "Manila",
  "Quezon City",
  "Caloocan",
  "Las Piñas",
  "Makati",
  "Malabon",
  "Mandaluyong",
  "Marikina",
  "Muntinlupa",
  "Navotas",
  "Parañaque",
  "Pasay",
  "Pasig",
  "Pateros",
  "San Juan",
  "Taguig",
  "Valenzuela",
  // Region I – Ilocos
  "Laoag",
  "Batac",
  "Candon",
  "Vigan",
  "San Fernando (La Union)",
  "Dagupan",
  "Alaminos",
  "Urdaneta",
  "San Carlos (Pangasinan)",
  // Region II – Cagayan Valley
  "Tuguegarao",
  "Cauayan",
  "Ilagan",
  "Santiago",
  // Region III – Central Luzon
  "Balanga",
  "Malolos",
  "Meycauayan",
  "San Jose del Monte",
  "Cabanatuan",
  "Gapan",
  "Muñoz",
  "Palayan",
  "San Jose (Nueva Ecija)",
  "Angeles",
  "San Fernando (Pampanga)",
  "Mabalacat",
  "Olongapo",
  "Tarlac City",
  // Region IV-A – CALABARZON
  "Batangas City",
  "Lipa",
  "Tanauan",
  "Santo Tomas (Batangas)",
  "Bacoor",
  "Cavite City",
  "Dasmariñas",
  "General Trias",
  "Imus",
  "Tagaytay",
  "Trece Martires",
  "Biñan",
  "Cabuyao",
  "Calamba",
  "San Pablo",
  "San Pedro",
  "Santa Rosa",
  "Antipolo",
  "Cainta",
  "Taytay",
  "Rodriguez (Montalban)",
  "Lucena",
  "Tayabas",
  // Region IV-B – MIMAROPA
  "Calapan",
  "Puerto Princesa",
  // Region V – Bicol
  "Legazpi",
  "Ligao",
  "Tabaco",
  "Iriga",
  "Naga (Camarines Sur)",
  "Masbate City",
  "Sorsogon City",
  // Region VI – Western Visayas
  "Iloilo City",
  "Passi",
  "Bacolod",
  "Bago",
  "Cadiz",
  "Escalante",
  "Himamaylan",
  "Kabankalan",
  "La Carlota",
  "Sagay",
  "San Carlos (Negros Occidental)",
  "Silay",
  "Sipalay",
  "Talisay (Negros Occidental)",
  "Victorias",
  "Roxas City",
  // Region VII – Central Visayas
  "Cebu City",
  "Lapu-Lapu",
  "Mandaue",
  "Carcar",
  "Danao",
  "Naga (Cebu)",
  "Talisay (Cebu)",
  "Toledo",
  "Bogo",
  "Tagbilaran",
  "Dumaguete",
  "Bayawan",
  "Bais",
  "Canlaon",
  "Guihulngan",
  "Tanjay",
  // Region VIII – Eastern Visayas
  "Tacloban",
  "Ormoc",
  "Baybay",
  "Calbayog",
  "Catbalogan",
  "Maasin",
  // Region IX – Zamboanga Peninsula
  "Zamboanga City",
  "Dapitan",
  "Dipolog",
  "Isabela (Basilan)",
  "Pagadian",
  // Region X – Northern Mindanao
  "Cagayan de Oro",
  "El Salvador",
  "Iligan",
  "Malaybalay",
  "Valencia",
  "Oroquieta",
  "Ozamiz",
  "Tangub",
  "Gingoog",
  // Region XI – Davao
  "Davao City",
  "Digos",
  "Island Garden City of Samal",
  "Mati",
  "Panabo",
  "Tagum",
  // Region XII – SOCCSKSARGEN
  "General Santos",
  "Koronadal",
  "Tacurong",
  "Kidapawan",
  "Cotabato City",
  // Region XIII – Caraga
  "Butuan",
  "Cabadbaran",
  "Bayugan",
  "Bislig",
  "Surigao City",
  "Tandag",
  // CAR
  "Baguio",
  "Tabuk",
  // BARMM
  "Marawi",
  "Lamitan",
];

export const PH_PROVINCES: string[] = [
  "Abra",
  "Agusan del Norte",
  "Agusan del Sur",
  "Aklan",
  "Albay",
  "Antique",
  "Apayao",
  "Aurora",
  "Basilan",
  "Bataan",
  "Batanes",
  "Batangas",
  "Benguet",
  "Biliran",
  "Bohol",
  "Bukidnon",
  "Bulacan",
  "Cagayan",
  "Camarines Norte",
  "Camarines Sur",
  "Camiguin",
  "Capiz",
  "Catanduanes",
  "Cavite",
  "Cebu",
  "Cotabato",
  "Davao de Oro",
  "Davao del Norte",
  "Davao del Sur",
  "Davao Occidental",
  "Davao Oriental",
  "Dinagat Islands",
  "Eastern Samar",
  "Guimaras",
  "Ifugao",
  "Ilocos Norte",
  "Ilocos Sur",
  "Iloilo",
  "Isabela",
  "Kalinga",
  "La Union",
  "Laguna",
  "Lanao del Norte",
  "Lanao del Sur",
  "Leyte",
  "Maguindanao del Norte",
  "Maguindanao del Sur",
  "Marinduque",
  "Masbate",
  "Metro Manila",
  "Misamis Occidental",
  "Misamis Oriental",
  "Mountain Province",
  "Negros Occidental",
  "Negros Oriental",
  "Northern Samar",
  "Nueva Ecija",
  "Nueva Vizcaya",
  "Occidental Mindoro",
  "Oriental Mindoro",
  "Palawan",
  "Pampanga",
  "Pangasinan",
  "Quezon",
  "Quirino",
  "Rizal",
  "Romblon",
  "Samar",
  "Sarangani",
  "Siquijor",
  "Sorsogon",
  "South Cotabato",
  "Southern Leyte",
  "Sultan Kudarat",
  "Sulu",
  "Surigao del Norte",
  "Surigao del Sur",
  "Tarlac",
  "Tawi-Tawi",
  "Zambales",
  "Zamboanga del Norte",
  "Zamboanga del Sur",
  "Zamboanga Sibugay",
];
