export type BackendSupportStatus = "wired" | "partial" | "local" | "blocked";

export interface BackendSupportItem {
  area: string;
  screen: string;
  status: BackendSupportStatus;
  currentSupport: string;
  existingEndpoints: string[];
  backendNeeded: string[];
  notes: string;
}

export const backendSupportMatrix: BackendSupportItem[] = [
  {
    area: "Authentication",
    screen: "Login",
    status: "wired",
    currentSupport: "Supabase password sign-in followed by gateway admin validation.",
    existingEndpoints: ["POST /auth/v1/token?grant_type=password", "GET /v1/me"],
    backendNeeded: [],
    notes: "Non-admin or inactive users are rejected in the admin frontend.",
  },
  {
    area: "Dashboard",
    screen: "Overview",
    status: "wired",
    currentSupport: "Live payments, support tickets, catalog counts, provider listing counts, booking stats, user summary, derived activity, and real-time operations alerts.",
    existingEndpoints: [
      "GET /v1/admin/payments",
      "GET /v1/admin/support/tickets",
      "GET /v1/catalog/categories",
      "GET /v1/catalog/services",
      "GET /v1/catalog/providers",
      "GET /v1/admin/bookings/summary",
      "GET /v1/admin/users/summary",
      "GET /v1/admin/bookings/operations/alerts",
    ],
    backendNeeded: [],
    notes: "All dashboard data including operations alerts now wired to backend.",
  },
  {
    area: "Finance",
    screen: "Transactions",
    status: "wired",
    currentSupport: "Lists payments, filters records, exports CSV, updates payment status, and fetches individual payment detail.",
    existingEndpoints: [
      "GET /v1/admin/payments",
      "GET /v1/admin/payments/:paymentId",
      "PATCH /v1/admin/payments/:paymentId/status",
    ],
    backendNeeded: [],
    notes: "Full payment management is now wired.",
  },
  {
    area: "Finance",
    screen: "Failed Payments",
    status: "partial",
    currentSupport: "Derives refunded/cancelled payment exceptions from admin payments.",
    existingEndpoints: ["GET /v1/admin/payments", "GET /v1/admin/payments/failures"],
    backendNeeded: [],
    notes: "Failure reason, gateway code, retry history, and dispute linkage need dedicated backend fields.",
  },
  {
    area: "Support",
    screen: "Support",
    status: "wired",
    currentSupport: "Full support ticket management: list, detail, status updates, thread replies, and agent assignment.",
    existingEndpoints: [
      "GET /v1/admin/support/tickets",
      "GET /v1/admin/support/tickets/:ticketId",
      "PATCH /v1/admin/support/tickets/:ticketId/status",
      "GET /v1/admin/support/tickets/:ticketId/replies",
      "POST /v1/admin/support/tickets/:ticketId/replies",
      "PATCH /v1/admin/support/tickets/:ticketId/assignee",
    ],
    backendNeeded: [],
    notes: "Full support ticket workflow including replies and assignee management is now wired.",
  },
  {
    area: "Marketplace",
    screen: "Categories",
    status: "wired",
    currentSupport: "Full admin category management: list with isActive/sortOrder, create, update, and delete.",
    existingEndpoints: [
      "GET /v1/catalog/categories",
      "GET /v1/admin/catalog/categories",
      "POST /v1/admin/catalog/categories",
      "PATCH /v1/admin/catalog/categories/:id",
      "DELETE /v1/admin/catalog/categories/:id",
    ],
    backendNeeded: [],
    notes: "Admin category CRUD is now fully wired.",
  },
  {
    area: "Marketplace",
    screen: "Services",
    status: "wired",
    currentSupport: "Full admin service management: list with isActive, create, update, and delete.",
    existingEndpoints: [
      "GET /v1/catalog/services",
      "GET /v1/admin/catalog/services",
      "POST /v1/admin/catalog/services",
      "PATCH /v1/admin/catalog/services/:id",
      "DELETE /v1/admin/catalog/services/:id",
    ],
    backendNeeded: [],
    notes: "Admin service CRUD is now fully wired.",
  },
  {
    area: "Providers",
    screen: "Service Providers",
    status: "wired",
    currentSupport: "Full admin provider management: list with user details, get profile, and update verification/suspension status.",
    existingEndpoints: [
      "GET /v1/catalog/providers",
      "GET /v1/admin/providers",
      "GET /v1/admin/providers/:id",
      "PATCH /v1/admin/providers/:id/status",
    ],
    backendNeeded: [],
    notes: "Admin provider endpoints now expose full user details, contact number, and status management.",
  },
  {
    area: "Providers",
    screen: "Provider Applications",
    status: "partial",
    currentSupport: "Backend exposes live provider profile applications and approve/reject verification decisions. Document endpoint returns 501 stub.",
    existingEndpoints: [
      "GET /v1/admin/provider-applications",
      "GET /v1/admin/provider-applications/:id",
      "POST /v1/admin/provider-applications/:id/approve",
      "POST /v1/admin/provider-applications/:id/reject",
      "GET /v1/admin/provider-applications/:id/documents/:documentId",
    ],
    backendNeeded: [],
    notes: "Document preview/download stub returns 501. A storage-backed contract is needed to serve actual files.",
  },
  {
    area: "Operations",
    screen: "Bookings and Ongoing Services",
    status: "partial",
    currentSupport: "Lists platform bookings and supports admin cancellation/escalation through backend APIs. Provider messaging stub returns 501.",
    existingEndpoints: [
      "GET /v1/admin/bookings",
      "GET /v1/admin/bookings/:id",
      "POST /v1/admin/bookings/:id/cancel",
      "POST /v1/admin/bookings/:id/escalate",
      "POST /v1/admin/bookings/:id/provider-messages",
    ],
    backendNeeded: [],
    notes: "Provider messaging stub returns 501. A dedicated messaging-service contract is needed for real delivery.",
  },
  {
    area: "Finance",
    screen: "Payouts, Refunds, Settlements, Commission",
    status: "partial",
    currentSupport: "Payout requests and refund review are backend-backed with admin mutations and audit logs. Settlement approval stub returns 501.",
    existingEndpoints: [
      "GET /v1/admin/payments/payouts",
      "PATCH /v1/admin/payments/payouts/:payoutId/status",
      "GET /v1/admin/refunds",
      "POST /v1/admin/refunds/:id/approve",
      "POST /v1/admin/refunds/:id/reject",
      "GET /v1/admin/commission-rules",
      "PATCH /v1/admin/commission-rules/:id",
      "POST /v1/admin/settlements/:id/approve",
    ],
    backendNeeded: [],
    notes: "Settlement approval stub returns 501. A settlement service contract is needed for real processing.",
  },
  {
    area: "Marketing",
    screen: "Promotions and Broadcasts",
    status: "partial",
    currentSupport: "Promotion code listing and create/update/delete APIs are backend-backed. Broadcast endpoint stub returns 501.",
    existingEndpoints: [
      "GET /v1/admin/promotions",
      "POST /v1/admin/promotions",
      "PATCH /v1/admin/promotions/:id",
      "DELETE /v1/admin/promotions/:id",
      "POST /v1/admin/broadcasts",
    ],
    backendNeeded: [],
    notes: "Broadcast stub returns 501. Audience targeting, scheduling, and delivery need a broadcast service contract.",
  },
  {
    area: "Account",
    screen: "Settings",
    status: "wired",
    currentSupport: "Preferences load from and save to shared user preference backend.",
    existingEndpoints: ["GET /v1/me/preferences", "PUT /v1/me/preferences"],
    backendNeeded: [],
    notes: "Theme, timezone, retention, and alert toggles are stored in preference metadata.",
  },
  {
    area: "Account",
    screen: "Profile and Security",
    status: "partial",
    currentSupport: "Profile and password updates call shared account backend endpoints. 2FA stubs return 501; sessions returns empty array.",
    existingEndpoints: [
      "GET /v1/me",
      "PATCH /v1/me",
      "PATCH /v1/me/password",
      "POST /v1/me/two-factor/enable",
      "POST /v1/me/two-factor/disable",
      "GET /v1/me/sessions",
    ],
    backendNeeded: [],
    notes: "2FA stubs return 501. Sessions endpoint returns empty array. TOTP/SMS and real session tracking need a dedicated auth contract.",
  },
  {
    area: "Reports",
    screen: "Reports and Analytics",
    status: "partial",
    currentSupport: "Revenue report can export live payment rows. Report generation stubs return 501.",
    existingEndpoints: [
      "GET /v1/admin/payments",
      "GET /v1/admin/reports/revenue.pdf",
      "GET /v1/admin/reports/bookings.csv",
      "POST /v1/admin/reports/:type",
      "POST /v1/admin/reports/:type/schedules",
    ],
    backendNeeded: [],
    notes: "All report stubs return 501. PDF rendering, CSV generation, and scheduled reports need backend workers.",
  },
  {
    area: "Platform",
    screen: "Admin Roles, Audit Trail, Integrations",
    status: "partial",
    currentSupport: "Audit Trail lists and exports backend audit logs; user listing and status management are wired. User creation and integration stubs return 501.",
    existingEndpoints: [
      "GET /v1/admin/audit-logs",
      "GET /v1/admin/audit-logs/export",
      "GET /v1/admin/users",
      "GET /v1/admin/users/summary",
      "PATCH /v1/admin/users/:userId/status",
      "POST /v1/admin/users",
      "PATCH /v1/admin/integrations/:provider/credentials",
      "POST /v1/admin/integrations/:provider/test",
    ],
    backendNeeded: [],
    notes: "Admin user creation and integration management stubs return 501. Real role assignment and credential storage need dedicated contracts.",
  },
];
