export type BackendSupportStatus = "wired";

export interface BackendSupportItem {
  area: string;
  screen: string;
  status: BackendSupportStatus;
  currentSupport: string;
  existingEndpoints: string[];
  backendNeeded: string[];
  notes: string;
}

export const backendSupportMatrix: BackendSupportItem[] = [
  {
    area: "Authentication",
    screen: "Login and Password Reset",
    status: "wired",
    currentSupport: "Supabase password sign-in followed by gateway admin validation. Forgot Password submits through the gateway-backed password reset endpoint.",
    existingEndpoints: [
      "POST /auth/v1/token?grant_type=password",
      "GET /v1/me",
      "POST /v1/auth/password-reset",
    ],
    backendNeeded: [],
    notes: "Non-admin or inactive users are rejected in the admin frontend. The unauthenticated admin-access request modal was removed; new admin accounts are created by Super Admins from Admin Roles.",
  },
  {
    area: "Dashboard",
    screen: "Overview",
    status: "wired",
    currentSupport: "Live payments, support tickets, catalog counts, provider listing counts, booking stats, user summary, derived activity, and real-time operations alerts.",
    existingEndpoints: [
      "GET /v1/admin/payments",
      "GET /v1/admin/support/tickets",
      "GET /v1/catalog/categories",
      "GET /v1/catalog/services",
      "GET /v1/catalog/providers",
      "GET /v1/admin/bookings/summary",
      "GET /v1/admin/users/summary",
      "GET /v1/admin/bookings/operations/alerts",
    ],
    backendNeeded: [],
    notes: "All dashboard data including operations alerts now wired to backend.",
  },
  {
    area: "Finance",
    screen: "Transactions",
    status: "wired",
    currentSupport: "Lists payments, filters records, exports CSV, updates payment status, and fetches individual payment detail.",
    existingEndpoints: [
      "GET /v1/admin/payments",
      "GET /v1/admin/payments/:paymentId",
      "PATCH /v1/admin/payments/:paymentId/status",
    ],
    backendNeeded: [],
    notes: "Full payment management is now wired.",
  },
  {
    area: "Finance",
    screen: "Failed Payments",
    status: "wired",
    currentSupport: "Lists cancelled/refunded payments with editable failure reason, gateway code, retry history, dispute linkage, and a retry action that resets the payment to pending.",
    existingEndpoints: [
      "GET /v1/admin/payments",
      "GET /v1/admin/payments/failures",
      "POST /v1/admin/payments/:paymentId/failure",
      "POST /v1/admin/payments/:paymentId/retry",
    ],
    backendNeeded: [],
    notes: "Payments table now has failure_reason, failure_code, retry_count, last_retry_at, dispute_id columns. Admin can record failure metadata and re-queue failed payments through dedicated RPC functions.",
  },
  {
    area: "Support",
    screen: "Support",
    status: "wired",
    currentSupport: "Full support ticket management: list, detail, status updates, thread replies, and agent assignment.",
    existingEndpoints: [
      "GET /v1/admin/support/tickets",
      "GET /v1/admin/support/tickets/:ticketId",
      "PATCH /v1/admin/support/tickets/:ticketId/status",
      "GET /v1/admin/support/tickets/:ticketId/replies",
      "POST /v1/admin/support/tickets/:ticketId/replies",
      "PATCH /v1/admin/support/tickets/:ticketId/assignee",
    ],
    backendNeeded: [],
    notes: "Full support ticket workflow including replies and assignee management is now wired. Customers can also view and post replies from mobile via /v1/support/tickets/:id/replies.",
  },
  {
    area: "Marketplace",
    screen: "Categories",
    status: "wired",
    currentSupport: "Full admin category management: list with isActive/sortOrder, create, update, and delete.",
    existingEndpoints: [
      "GET /v1/catalog/categories",
      "GET /v1/admin/catalog/categories",
      "POST /v1/admin/catalog/categories",
      "PATCH /v1/admin/catalog/categories/:id",
      "DELETE /v1/admin/catalog/categories/:id",
    ],
    backendNeeded: [],
    notes: "Admin category CRUD is now fully wired.",
  },
  {
    area: "Marketplace",
    screen: "Services",
    status: "wired",
    currentSupport: "Full admin service management: list with isActive, create, update, and delete.",
    existingEndpoints: [
      "GET /v1/catalog/services",
      "GET /v1/admin/catalog/services",
      "POST /v1/admin/catalog/services",
      "PATCH /v1/admin/catalog/services/:id",
      "DELETE /v1/admin/catalog/services/:id",
    ],
    backendNeeded: [],
    notes: "Admin service CRUD is now fully wired.",
  },
  {
    area: "Marketplace",
    screen: "Service Areas",
    status: "wired",
    currentSupport: "Read-only coverage view derives service-area provider counts from live provider listings.",
    existingEndpoints: ["GET /v1/admin/providers"],
    backendNeeded: [],
    notes: "Service-area CRUD controls were removed because no persisted service-area contract exists yet.",
  },
  {
    area: "Providers",
    screen: "Service Providers",
    status: "wired",
    currentSupport: "Full admin provider management: list with user details, get profile, and update verification/suspension status.",
    existingEndpoints: [
      "GET /v1/catalog/providers",
      "GET /v1/admin/providers",
      "GET /v1/admin/providers/:id",
      "PATCH /v1/admin/providers/:id/status",
    ],
    backendNeeded: [],
    notes: "Admin provider endpoints now expose full user details, contact number, and status management.",
  },
  {
    area: "Providers",
    screen: "Provider Applications",
    status: "wired",
    currentSupport: "Backend exposes live provider profile applications, approve/reject verification decisions, provider document preview/download URLs, and request-info notifications through the gateway.",
    existingEndpoints: [
      "GET /v1/admin/provider-applications",
      "GET /v1/admin/provider-applications/:id",
      "POST /v1/admin/provider-applications/:id/approve",
      "POST /v1/admin/provider-applications/:id/reject",
      "POST /v1/admin/provider-applications/:id/request-info",
      "GET /v1/admin/provider-applications/:id/documents/:documentId",
      "GET /v1/admin/provider-applications/:id/documents/:documentId/download",
    ],
    backendNeeded: [],
    notes: "Document endpoints return provider_catalog.provider_documents metadata and signed storage URLs when only storage_path is available. Request-info sends a provider notification and audit log.",
  },
  {
    area: "Operations",
    screen: "Reviews moderation",
    status: "wired",
    currentSupport:
      "Lists every review across providers, supports rating distribution and flag filter, and lets admins hide or restore reviews end-to-end.",
    existingEndpoints: [
      "GET /v1/admin/reviews",
      "PATCH /v1/admin/reviews/:reviewId/flag",
    ],
    backendNeeded: [],
    notes:
      "Backed by review-service internal admin routes (list, set flag). Mobile-created reviews and provider replies now have an admin moderation surface.",
  },
  {
    area: "Users",
    screen: "Customers",
    status: "wired",
    currentSupport:
      "Customers page lists every customer-role user with live status, signup date, contact, and search across name/email/phone/ID.",
    existingEndpoints: [
      "GET /v1/admin/users?role=customer",
      "GET /v1/admin/users/summary",
    ],
    backendNeeded: [],
    notes:
      "Per-customer booking and revenue aggregates are not yet exposed; admin Dashboard surfaces platform-wide booking and revenue metrics instead.",
  },
  {
    area: "Providers",
    screen: "Availability viewer",
    status: "wired",
    currentSupport:
      "Service Provider Details → Availability tab loads the live weekly windows and upcoming days off through the existing public schedule endpoint.",
    existingEndpoints: ["GET /v1/provider/availability/:providerId"],
    backendNeeded: [],
    notes:
      "Read-only on the admin side today; mutations stay with the provider via /v1/provider/availability/windows and /v1/provider/availability/days-off.",
  },
  {
    area: "Providers",
    screen: "Portfolio moderation",
    status: "wired",
    currentSupport:
      "Service Provider Details → Portfolio tab loads live media for the provider and lets admins remove any inappropriate item with an audit log entry.",
    existingEndpoints: [
      "GET /v1/admin/providers/:providerId/portfolio",
      "DELETE /v1/admin/providers/:providerId/portfolio/:mediaId",
    ],
    backendNeeded: [],
    notes:
      "Admin endpoints reuse the catalog-service portfolio routes; deletes resolve the provider's owner userId via getProvider and write an admin audit log.",
  },
  {
    area: "Operations",
    screen: "Bookings and Ongoing Services",
    status: "wired",
    currentSupport: "Lists platform bookings, supports admin cancellation, escalation, and provider notification messages. Provider messages persist into a per-booking admin thread that can be listed and appended via dedicated endpoints.",
    existingEndpoints: [
      "GET /v1/admin/bookings",
      "GET /v1/admin/bookings/:id",
      "POST /v1/admin/bookings/:id/cancel",
      "POST /v1/admin/bookings/:id/escalate",
      "POST /v1/admin/bookings/:id/provider-messages",
      "GET /v1/admin/bookings/:id/messages",
      "POST /v1/admin/bookings/:id/messages",
    ],
    backendNeeded: [],
    notes: "Admin booking messages are stored in booking.admin_booking_messages with role-tagged entries (admin/provider/customer). The OngoingServices contact modal renders the persisted thread and provider notifications carry the persisted messageId.",
  },
  {
    area: "Finance",
    screen: "Payouts, Refunds, Settlements, Commission",
    status: "wired",
    currentSupport: "Payout requests, payment release, refund review, settlement list/approve/reject actions, settlement history, and manual bank-reference reconciliation are backend-backed with admin mutations and audit logs.",
    existingEndpoints: [
      "GET /v1/admin/payments/payouts",
      "POST /v1/admin/payments/:paymentId/release",
      "PATCH /v1/admin/payments/payouts/:payoutId/status",
      "GET /v1/admin/refunds",
      "POST /v1/admin/refunds/:id/approve",
      "POST /v1/admin/refunds/:id/reject",
      "GET /v1/admin/commission-rules",
      "PATCH /v1/admin/commission-rules/:id",
      "GET /v1/admin/settlements",
      "POST /v1/admin/settlements/:id/approve",
      "POST /v1/admin/settlements/:id/reject",
      "GET /v1/admin/settlements/:id/history",
      "POST /v1/admin/settlements/:id/reconcile",
    ],
    backendNeeded: [],
    notes: "Settlement list uses payout summaries as the settlement source of truth. Payment release creates a processing payout; approval, rejection, release history, and bank-reference reconciliation are backed by payout events and admin audit logs. External disbursement execution is intentionally not implied by the admin UI.",
  },
  {
    area: "Marketing",
    screen: "Promotions and Broadcasts",
    status: "wired",
    currentSupport: "Promotion code listing and create/update/delete APIs are backend-backed. Broadcasts send or schedule gateway-backed in-app, email, and SMS notifications to active role-based audiences.",
    existingEndpoints: [
      "GET /v1/admin/promotions",
      "POST /v1/admin/promotions",
      "PATCH /v1/admin/promotions/:id",
      "DELETE /v1/admin/promotions/:id",
      "GET /v1/admin/broadcasts",
      "POST /v1/admin/broadcasts",
    ],
    backendNeeded: [],
    notes: "Broadcast delivery records history, scheduled sends, repeat intent, selected delivery channels, and optional cohort filters.",
  },
  {
    area: "Account",
    screen: "Settings",
    status: "wired",
    currentSupport: "Preferences load from and save to shared user preference backend.",
    existingEndpoints: ["GET /v1/me/preferences", "PUT /v1/me/preferences"],
    backendNeeded: [],
    notes: "Theme, timezone, retention, and alert toggles are stored in preference metadata.",
  },
  {
    area: "Account",
    screen: "Profile and Security",
    status: "wired",
    currentSupport: "Profile and password updates call shared account backend endpoints. Sessions endpoint returns Supabase auth.users.last_sign_in_at-derived session records. 2FA now provisions a TOTP secret and QR code, verifies setup, and disables with a current code.",
    existingEndpoints: [
      "GET /v1/me",
      "PATCH /v1/me",
      "PATCH /v1/me/password",
      "POST /v1/me/two-factor/enable",
      "POST /v1/me/two-factor/verify",
      "POST /v1/me/two-factor/disable",
      "GET /v1/me/sessions",
    ],
    backendNeeded: [],
    notes: "Sessions endpoint is wired to auth.users via servease_list_user_sessions RPC. 2FA state is owned by auth-service and stored on identity_and_user.users.",
  },
  {
    area: "Reports",
    screen: "Reports and Analytics",
    status: "wired",
    currentSupport: "Bookings, revenue, users, and financial CSV/PDF exports stream gateway-backed data. Booking, revenue, provider, and customer report insights render gateway-derived users, providers, reviews, and payment rows without demo fallback. Report generation returns ready download metadata, scheduled reports persist/list schedule metadata, and admin-service can email due report download links through APICenter.",
    existingEndpoints: [
      "GET /v1/admin/payments",
      "GET /v1/admin/reports/revenue.pdf",
      "GET /v1/admin/reports/revenue.csv",
      "GET /v1/admin/reports/users.csv",
      "GET /v1/admin/reports/financial.csv",
      "GET /v1/admin/reports/bookings.csv",
      "POST /v1/admin/reports/:type",
      "POST /v1/admin/reports/:type/schedules",
      "GET /v1/admin/reports/:type/schedules",
    ],
    backendNeeded: [],
    notes: "Report endpoints validate the supported report types (bookings, revenue, users, financial), CSV/PDF format, frequency, and recipients. Schedule metadata and delivery state are stored in admin.report_schedules; the optional worker is enabled with ADMIN_REPORT_DELIVERY_WORKER_ENABLED=true and uses @implementsprint/sdk emailSend. Schedule edit/pause/resume controls and unsupported performance/compliance report wrappers were removed until matching backend contracts exist.",
  },
  {
    area: "Platform",
    screen: "Admin Roles, Audit Trail, Integrations",
    status: "wired",
    currentSupport: "Audit Trail lists and exports backend audit logs; admin user listing, creation, access-role updates, status management, and deletion are wired. Integrations page reads, toggles, and tests live integration records.",
    existingEndpoints: [
      "GET /v1/admin/audit-logs",
      "GET /v1/admin/audit-logs/export",
      "GET /v1/admin/users",
      "GET /v1/admin/users/summary",
      "PATCH /v1/admin/users/:userId/status",
      "PATCH /v1/admin/users/:userId/access",
      "DELETE /v1/admin/users/:userId",
      "POST /v1/admin/users",
      "GET /v1/admin/integrations",
      "PATCH /v1/admin/integrations/:provider/credentials",
      "POST /v1/admin/integrations/:provider/test",
    ],
    backendNeeded: [],
    notes: "Integrations are stored in admin.integrations table with audit_logs trail. Admin access roles are fixed backend-defined roles. Custom permission editing and admin password-reset resend are intentionally not shown until dedicated backend contracts exist.",
  },
];
